apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-api-users
  name: test-api-users
  labels:
    app: test-api-users
spec:
  selector:
    matchLabels:
      app: test-api-users
  template:
    metadata:
      labels:
        app: test-api-users
        name: test-api-users
    spec:
      containers:
        - name: test-api-users
          image: krishnamccompage/MC-Test/test-api-users
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 9001
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        